<footer>
  <section id="contatti">
    <h1>Contatti</h1>
    <p style="margin: 0;">
       Email: support@fantafoot.com<br>
       Telefono: +39 800 800 8080<br>
       Indirizzo: Piazza Trento Trieste 1, 44123 Ferrara, Italia
    </p>
  </section>
  <section id="social">
    <h1>Social</h1>
    <article>
      <a>Facebook</a> |
      <a>Twitter</a> |
      <a>Instagram</a> |
      <a>TikTok</a>
    </article>
  </section>
  <section id="info">
    <h1>Informazioni</h1>
    <article>
      <a>Accessibility</a> |
      <a>Privacy Policy</a> |
      <a>Cookie Policy</a> |
      <a>Terms and conditions</a>
    </article>
  </section>
  <section id="copyright">
    <p>&copy; 2024 FantaFoot. Tutti i diritti riservati.</p>
  </section>
</footer>